name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}  
      - run: npm ci
      - run: npm run build --if-present
  test:
  
    name: Test environment for MySQL
    runs-on: ubuntu-latest
    steps:
    - uses: gtadam/mysql-deploy-action@v1
      with:
        DATABASE_HOST: ${{secrets.MYSQL_HOST}}
        DATABASE_PORT: '3306'
        DATABASE_NAME: 'studenthome'
        DATABASE_USERNAME: ${{secrets.MYSQL_USERNAME}}
        DATABASE_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
        DATABASE_SCRIPT: 'studenthome.sql'
    - run: npm coverage

  sonarQubeTrigger:
  
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: sijomc/sonarscan-action@master
      with:
        host: ${{secrets.SONAR_URL}}
        login: ${{secrets.SONAR_LOGIN_KEY}}
      
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} 
          heroku_email: ${{secrets.STUDENT_EMAIL}}
